Init
Teaching-projects/-SZE-MOSZE-2020-Bukottak_busszuja pull request #1
Opened 2020-09-13 23:20 UTC by tmate93

2020-09-15 13:51 UTC, hegyhati requested changes
Nem rejectelem, de van boven javitanivalo.

2020-09-15 13:51 UTC, hegyhati commented on Source.cpp
> +	Szorny s2("Sotet varazslo", 250, 40);
A kiirasnak megfeleloen parancssori argumentumokbol legyenek ezek beszedve.

2020-09-15 13:51 UTC, hegyhati commented on Source.cpp
> +	system("pause");
Ahogy irtam, ezert auto reject jar.

2020-09-15 13:51 UTC, hegyhati commented on Source.cpp
> +	s1.tamadas(s2);
A kod nem tul kifejezo igy, mert ez alapjan ugy tunik, hogy s1 1x megtamadja s2-t, az nem jon le belole, hogy ebbol oda-vissza csapkodas lesz halalig.

2020-09-15 13:51 UTC, hegyhati commented on Szorny.cpp
> +	this->dmg = c;
inicializalo lista.

2020-09-15 13:51 UTC, hegyhati commented on Szorny.cpp
> +}
ennek mi ertelme?

2020-09-15 13:51 UTC, hegyhati commented on Szorny.cpp
> +	return this->dmg;
minek this-> mindenutt?

2020-09-15 13:51 UTC, hegyhati commented on Szorny.cpp
> +}
Ilyen fuggveny ne legyen.

2020-09-15 13:51 UTC, hegyhati commented on Szorny.cpp
> +	if (a.getHp() == 0) cout << a.getName() << " meghalt. " << this->nev << " nyert." << endl;
ennek a logikanak a main-ben a helye igazabol.

2020-09-15 13:51 UTC, hegyhati commented on Szorny.h
> +	string nev;
constok? setHP-nak publikusan nem szabad lennie, privatban meg overengineering.

2020-09-16 18:50 UTC, tmate93 commented
@hegyhati elkészítettük a módosításokat a fentiek alapján

2020-09-16 23:39 UTC, hegyhati requested changes

2020-09-16 23:39 UTC, hegyhati commented on Source.cpp
> +int sti(char* c)
atoi?

2020-09-16 23:39 UTC, hegyhati commented on Source.cpp
> +	while (pont1 > 0 && pont2 > 0) {
nem, nem csinalunk masolatot, az objektumban ott van, hogy mennyi az annyi.

2020-09-16 23:39 UTC, hegyhati commented on Source.cpp
> +	while (pont1 > 0 && pont2 > 0) {
ha redundansan ket helyen is van az adat, abbol csak baj lehet. elmasznak egymas mellol, es nem ugy mukodik a program, ahogy kellene.

2020-09-16 23:39 UTC, hegyhati commented on Source.cpp
> +	cin.get();
tessek beallitani breakpointot, vagy a fejlesztokornyezetet ugy, hogy nyitva hagyja a terminalt.

2020-09-16 23:39 UTC, hegyhati commented on Szorny.cpp
> +}
ilyet a "logika" osztalyunkba ne tegyunk. A logika ne vegezzen user input/output muveletet.

2020-09-16 23:39 UTC, hegyhati commented on Szorny.cpp
> +void Szorny::tamad(Szorny & a) {
itt meg egy const elferne.

2020-09-16 23:39 UTC, hegyhati commented on Szorny.h
> +	int dmg;
const?

2020-09-16 23:39 UTC, hegyhati commented on Szorny.h
> +	Szorny(string a, int b, int c):nev(a),hp(b),dmg(c) {}
Amikor a szignaturat feldobja a fejlesztokornyezet, honnet fogod tudni, hogy a b a health es a c a dmg vagy forditva?

2020-09-18 18:50 UTC, tmate93 commented
@hegyhati Javítottuk a programot a fentiek alapján

2020-09-18 18:52 UTC, tmate93 commented on Source.cpp
> +int sti(char* c)
@hegyhati azért nem atoi-t használtam mert azzal nincs hibakezelsre lehetőség, nem ad vissza hibakódot, ha nem megfelellő az input akkor meghatározhatatlan a kimenete, és ezt a megoldást találtam helyette

2020-09-21 14:35 UTC, hegyhati commented on Source.cpp
> +int sti(char* c)
Gondolom bekopiztal valahonnet valami kodot, ami remeljuk szinten nem bugzik szelsoseges esetekre. De mostantol ez a TE kodod, Neked kell karban tartani, ha gubanc van benne, megkeresni. Az atoi standard. Illetve most meg hibakra valo felkeszitesrol nem volt szo, szoval feleslegesen komplikalod, de felolem maradhat.

2020-09-21 14:38 UTC, hegyhati requested changes
Par aprosag,a ztan mehet be.

2020-09-21 14:38 UTC, hegyhati commented on Source.cpp
> +void kiir(Szorny s) {
const, illetve minek masolod?

2020-09-21 14:38 UTC, hegyhati commented on Source.cpp
> +            kiir(s2);
indentalas

2020-09-21 14:38 UTC, hegyhati commented on Szorny.h
> +	int dmg;
const?

2020-09-21 14:38 UTC, hegyhati commented on Szorny.h
> +using namespace std;
logika osztalyban ne nagyon hasznaljunk using-ot.

2020-09-21 15:29 UTC, tmate93 commented
@hegyhati Elkészültek a módosítások.

const?

_Originally posted by @hegyhati in https://github.com/Teaching-projects/-SZE-MOSZE-2020-Bukottak_busszuja/pull/1#discussion_r492099675_

itt azért nincs const, mert bár jelenleg még nem, de mind a damage mind a health változhat így azok nem lehetnek constok

2020-09-22 06:26 UTC, hegyhati requested changes

2020-09-22 06:26 UTC, hegyhati commented on Source.cpp
> +    }
indentalas kisse szet van esve

2020-09-22 06:26 UTC, hegyhati commented on Source.cpp
> +	}
indentalas.

2020-09-22 06:26 UTC, hegyhati commented on Szorny.h
> +	int dmg;
ne probaljuk meg elore kitalalni, mi lesz, a feladat az volt, hogy ami lehet const, az legyen const. KEsobb ha valami megsem lesz const, majd kitoroljuk, es akkor annak a torlesnek ott abban a commitban lesz a helye, ahol beletettuk azt, ami miatt nem lehet ez const.

2020-09-22 18:38 UTC, tmate93 commented
@hegyhati javítva az indentálás és a változók constok ahol lehet

2020-09-22 23:46 UTC, hegyhati commented on Szorny.h
> +	const int dmg;
nekem ez tovabbra is szet van csuszva :-D

2020-09-22 23:46 UTC, hegyhati approved these changes

2020-09-22 23:46 UTC, merged