Refactor
Teaching-projects/-SZE-MOSZE-2020-Bukottak_busszuja pull request #11
Opened 2020-11-04 15:44 UTC by HabanAndras

@hegyhati ugy gondoljuk,kesz a refaktorálás!

2020-11-04 17:17 UTC, hegyhati requested changes

2020-11-04 17:17 UTC, hegyhati commented on JSON.h
> +    }
ez T=int/double-re nagyon csunyan el fog hasalni.

2020-11-04 17:17 UTC, hegyhati commented on Hero.cpp
> +  	double speed = stod(parsedJSON.getErtek("base_attack_cooldown"));
na itt (meg a monsterben ugyanitt) nem szabadna mar stoi-knak lennie. Illetve ezt a getErteket is felejtsetek el, erre van a get. ez a regi fuggveny mehet a kukaba.(ebbol lett az uj get).

2020-11-05 11:23 UTC, tmate93 commented
@hegyhati elkészültek a kért módosítások

2020-11-06 12:49 UTC, hegyhati requested changes
most latom, hogy a jsonparseretek tele van rpg logikaval. Ami nem jo, annak nem kellene tudnia semmit arrol, hogy mifele json-t parzol.

2020-11-06 12:49 UTC, hegyhati commented on JSON.cpp
> +                    } else if (key == "attack_cooldown" || key == "base_attack_cooldown" || key == "cooldown_multiplier_per_level") {
a json-nek semmi ilyesmirol nem szabad tudnia.

2020-11-06 19:41 UTC, tmate93 commented
@hegyhati átírtuk a Parsert a fentiek alapján

2020-11-08 12:59 UTC, hegyhati approved these changes

2020-11-08 12:59 UTC, hegyhati commented
Oldjatok fel a conflicteket, aztan bemehet.

2020-11-09 12:05 UTC, HabanAndras commented
@hegyhati ütközések feloldva!

2020-11-09 12:37 UTC, hegyhati commented
Finally! :-D M<inden commitodrol kaptam az e-mailt :-D

2020-11-09 12:37 UTC, merged

2020-11-09 12:50 UTC, HabanAndras commented
@hegyhati akkor gondolom én is, még nem mertem megnyitni :D bocsi :D