Docker
Teaching-projects/-SZE-MOSZE-2020-Bukottak_busszuja pull request #12
Opened 2020-11-11 19:45 UTC by HabanAndras

@hegyhati elkészült a docker feladat!

2020-11-12 09:51 UTC, hegyhati requested changes

2020-11-12 09:51 UTC, hegyhati commented on .github/workflows/main.yml
> +        run: g++-9 -Wall -Werror -std=c++17 *.cpp -o output
nono, a make-et ne dobjuk ki.

2020-11-12 11:32 UTC, HabanAndras commented on .github/workflows/main.yml
> +        run: g++-9 -Wall -Werror -std=c++17 *.cpp -o output
hoppá, próbálgatás közben kikerült és elfelejtettem visszatenni.

2020-11-12 11:32 UTC, HabanAndras commented
@hegyhati a probléma javítva!

2020-11-13 18:47 UTC, hegyhati approved these changes

2020-11-13 18:47 UTC, merged