Fajlkezeles
Teaching-projects/-SZE-MOSZE-2020-Bukottak_busszuja pull request #2
Opened 2020-09-24 21:21 UTC by HabanAndras

@hegyhati Második feladat kész.

2020-09-29 07:49 UTC, wajzy requested changes
Alakítsátok át a parseUnit-ot, hogy megfeleljen a feladatkiírásnak!

2020-09-29 07:49 UTC, wajzy commented on Source.cpp
> +            s2.parseUnit(f2);
Nem azt csináljátok, amit a feladat kér. "A harcosokert felelos osztalynak legyen egy statikus parseUnit fuggvenye, ami parameterkent var egy fajlnevet"

2020-09-30 09:59 UTC, HabanAndras commented on Source.cpp
> +            s2.parseUnit(f2);
@wajzy kész a javítás

2020-10-01 16:30 UTC, wajzy requested changes
Alakul, de a visszajelzéseknek megfelelően szeretnék még kérni egy kis polírozást.

2020-10-01 16:30 UTC, wajzy commented on Source.cpp
> +            throw 56;
Legyen a megnyitási problémák ellenőrzése a parseUnit feladata! Ha gond van, majd dob kivételt, amit a main try/catch-e elkaphat. Így most duplán van megnyitva ugyanaz a fájl, duplázódnak az ifstream objektumok, stb.

2020-10-01 16:30 UTC, wajzy commented on Source.cpp
> +                if (s1.getHp() > 0 && s2.getHp() > 0) {
Itt miért kell mindkét fél hp-jét vizsgálni? Nem csak s2-é csökken a támadás során? Ha s1 lemenne 0-ra, eleve el sem indítanánk a ciklusmagot.

2020-10-01 16:30 UTC, wajzy commented on Szorny.cpp
> +	}
Nagyon csúnyák ezek a varázskonstansok (12, -2, 9, 10, stb.). Igaz ugyan, hogy nem kértünk tökéletes input ellenőrzést, de azt tényleg nehéz elképzelni, hogy valaki a json fájlok megszerkesztésénél még a soron belüli oszloppozíciók megőrzésére is kínosan ügyelni fog. Sokkal szerencsésebb lenne a vezérlőjeleket keresni a karakterláncokban (idézőjelek, vesszők, kettőspont, ilyesmire gondolok), és az azonosított környezetben lévő adatokat kinyerni. Megtehetitek ezt később is, de előbb-utóbb úgyis foglalkozni kell majd ezzel.

A másik, hogy mennyivel jobb az érdekes részeket egy string-ekből álló vektorból kinyerni, mint abból a stringből, amibe a getline eleve olvasott?

2020-10-02 19:04 UTC, tmate93 commented
@wajzy Elkészültek a módosítások a kértek alapján

2020-10-05 08:40 UTC, wajzy approved these changes
@hegyhati Elfogadom a változtatásokat, azzal a megjegyzéssel, hogy fél év múlva, ha valaki megkérdezi majd, milyen problémát kódol az 57-es kilépési kód, szerintem fogalmatok sem lesz. Ez most nem tartozik ugyan szorosan a feladathoz, de legközelebb cseréljétek le a varázskonstansokat legalább egy szimbolikus állandóra, aminek valamilyen "beszédes" neve van, ha jobb nem jut eszetekbe.

2020-10-05 20:40 UTC, merged