Levelup
Teaching-projects/-SZE-MOSZE-2020-Bukottak_busszuja pull request #3
Opened 2020-10-15 11:24 UTC by tmate93

2020-10-15 11:31 UTC, tmate93 commented on Source.cpp
> +		Kalandor s1(Szorny::parseUnit(argv[1]));
@oliverosz Sikerült átírnunk a kódot, hogy lefusson a valgrind, viszont nem igazán értjük mi volt a probléma, valami az argv[1] el nem tetszett neki, mert amikor azzal a paraméterrel hívjuk meg az első parseunitot elszáll az említett hibával a valgrind, viszont ha felcseréljük a sorrendet akkor már lefut

2020-10-15 11:33 UTC, tmate93 commented on Szorny.cpp
>      std::ifstream f(fajlnev);
@oliverosz itt azt vettem észre, hogy amikor a valgrind fut le a fajlnev változóba bekerül egy DOTNET_NOLOGO="1" karaktersor és ezt sem igazán értem miért

2020-10-17 14:00 UTC, oliverosz requested changes

2020-10-17 14:00 UTC, oliverosz commented on Kalandor.h
> +	void xpGain();
Ez a 2 metódus meg a tagváltozók ne legyenek publikusak.

2020-10-17 14:00 UTC, oliverosz commented on Kalandor.h
> +	Kalandor(Szorny sz);
`const std::string&`
`const Szorny&`

2020-10-17 14:00 UTC, oliverosz commented on Kalandor.cpp
> +	if (a.hp < 0) a.hp = 0;
Az xp számításánál is vegye figyelembe, hogy az ellenségnek esetleg kevesebb élete volt, és akkor kevesebb a tényleges bevitt sebzés.

2020-10-17 14:00 UTC, oliverosz commented on Kalandor.cpp
> +    xp = 0;
inicializáló lista
vagy mivel úgyis ugyanezen értékek vannak a másik konstruktorban is, mehet a deklarációhoz a default érték

2020-10-17 14:00 UTC, oliverosz commented on Kalandor.cpp
> +    this->lvl = 1;
Felesleges a sok `this->`

2020-10-17 14:00 UTC, oliverosz commented on Szorny.cpp
> +    this->dmg = dmg;
inicializáló lista

2020-10-17 14:01 UTC, oliverosz commented on Szorny.cpp
>      std::ifstream f(fajlnev);
Ezt én sem értem, mitől lehetett, én még nem találkoztam ilyennel.

2020-10-18 08:27 UTC, tmate93 commented
@oliverosz Elkészűltek a kért módosítások

2020-10-18 19:07 UTC, oliverosz requested changes
A sebzés kiszámítása hibás. Ha javítottad, utána frissítsd a branchet a masterre és oldd fel a conflictokat.

2020-10-18 19:07 UTC, oliverosz commented on Kalandor.cpp
> +	xpGain(gain);
Ezt tessék átgondolni még egyszer.

2020-10-19 12:50 UTC, tmate93 commented
@oliverosz feloldottam a conflict-okat

2020-10-19 15:29 UTC, oliverosz approved these changes

2020-10-19 15:29 UTC, merged